download_url: https://HKXUPITD30368.hk.bocigroup.com/api/galaxy/v3/plugin/ansible/content/published/collections/artifacts/community-vmware-6.0.0.tar.gz
format_version: 1.0.0
name: vmware
namespace: community
server: https://HKXUPITD30368.hk.bocigroup.com/api/galaxy/
signatures: []
version: 6.0.0
version_url: /api/galaxy/v3/plugin/ansible/content/published/collections/index/community/vmware/versions/6.0.0/
