---
- name: Get passwords from CyberArk for all inventory hosts and execute tasks
  hosts: all
  gather_facts: false
  vars:
    cyberark_safe: "{{ cyberark_safe | default('Infra-Unix-Normal') }}"

  tasks:
    - name: Set cyberark_address with priority
      set_fact:
        cyberark_address: "{{ cyberark_address | default(ansible_host | default(inventory_hostname)) }}"
    
    - name: Set target_username with default
      set_fact:
        target_username: "{{ target_username | default('root') }}"

    - name: Authenticate with CyberArk
      cyberark.pas.cyberark_authentication:
        api_base_url: "{{ cyberark_api_base_url }}"
        username: "{{ cyberark_username | default(omit) }}"
        password: "{{ cyberark_password | default(omit) }}"
        validate_certs: "{{ cyberark_validate_certs | default(false) }}"
      delegate_to: localhost
      run_once: true
      when:
        - cyberark_username is defined
        - cyberark_password is defined

    - name: Build CyberArk query string
      set_fact:
        cyberark_query: "Safe={{ cyberark_safe }};UserName={{ target_username }};Address={{ cyberark_address }}"
    
    - name: Display CyberArk query parameters
      debug:
        msg:
          - "API Base URL: {{ cyberark_api_base_url }}"
          - "App ID: {{ cyberark_app_id }}"
          - "Safe: {{ cyberark_safe }}"
          - "Target Username: {{ target_username }}"
          - "Address: {{ cyberark_address }}"
          - "Query: {{ cyberark_query }}"

    - name: Retrieve password from CyberArk
      cyberark.pas.cyberark_credential:
        api_base_url: "{{ cyberark_api_base_url }}"
        app_id: "{{ cyberark_app_id }}"
        query: "{{ cyberark_query }}"
        validate_certs: "{{ cyberark_validate_certs | default(false) }}"
      register: target_credentials
      delegate_to: localhost
      ignore_errors: true
      failed_when: false
    
    - name: Verify password retrieved
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "Query: {{ cyberark_query }}"
          - "Password retrieved: {{ 'YES' if (target_credentials.result is defined and target_credentials.result.Content is defined and target_credentials.result.Content | length > 0) else 'NO' }}"
          - "Password length: {{ target_credentials.result.Content | length if (target_credentials.result is defined and target_credentials.result.Content is defined) else 0 }}"
      when: target_credentials is defined

    - name: Display detailed error information
      debug:
        msg:
          - "Error occurred while retrieving credentials"
          - "Error message: {{ target_credentials.msg | default('N/A') }}"
          - "Status code: {{ target_credentials.status_code | default('N/A') }}"
          - "Full result: {{ target_credentials | to_nice_json }}"
      when:
        - target_credentials is defined
        - target_credentials.failed | default(false)

    - name: Display credential retrieval status
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "Account: {{ target_username }}"
          - "Safe: {{ cyberark_safe }}"
          - "Status: {{ 'Retrieved' if (target_credentials.result is defined and target_credentials.result.Content is defined) else 'Failed' }}"
      when: target_credentials is defined

    - name: Set connection credentials
      set_fact:
        ansible_user: "{{ target_username }}"
        ansible_password: "{{ target_credentials.result.Content }}"
        ansible_become_password: "{{ target_credentials.result.Content }}"
      when: 
        - target_credentials is defined
        - target_credentials.result is defined
        - target_credentials.result.Content is defined
        - target_credentials.result.Content | length > 0

    - name: Hello World message
      debug:
        msg: "Hello World! Executing as {{ target_username }} on {{ inventory_hostname }}"
      when: 
        - target_credentials is defined
        - target_credentials.result is defined
        - target_credentials.result.Content is defined
        - target_credentials.result.Content | length > 0

    - name: Test connection as {{ target_username }}
      command: whoami
      register: whoami_result
      when: 
        - target_credentials is defined
        - target_credentials.result is defined
        - target_credentials.result.Content is defined
        - target_credentials.result.Content | length > 0

    - name: Display current user
      debug:
        msg: "Current user: {{ whoami_result.stdout }}"
      when: 
        - target_credentials is defined
        - target_credentials.result is defined
        - target_credentials.result.Content is defined
        - target_credentials.result.Content | length > 0
        - whoami_result is defined

    - name: Collect host information as {{ target_username }}
      command:
        argv:
          - bash
          - -lc
          - |
              echo '=== Hostname ==='
              hostname
              echo '=== Kernel & Arch ==='
              uname -a
              echo '=== Current User ==='
              id
              echo '=== IP Addresses ==='
              ip -o addr 2>/dev/null || ip addr
              echo '=== OS Release ==='
              cat /etc/os-release 2>/dev/null || echo "OS release info not available"
      register: host_info
      when: 
        - target_credentials is defined
        - target_credentials.result is defined
        - target_credentials.result.Content is defined
        - target_credentials.result.Content | length > 0
      ignore_errors: true

    - name: Show host information
      debug:
        msg: "{{ host_info.stdout }}"
      when: 
        - target_credentials is defined
        - target_credentials.result is defined
        - target_credentials.result.Content is defined
        - target_credentials.result.Content | length > 0
        - host_info is defined
        - host_info.stdout is defined

    - name: Credential retrieval failed
      debug:
        msg: "Warning: Failed to retrieve credentials for {{ target_username }}@{{ inventory_hostname }} from Safe {{ cyberark_safe }}. Skipping tasks for this host."
      when: 
        - target_credentials is not defined
          or target_credentials.result is not defined
          or target_credentials.result.Content is not defined
          or target_credentials.result.Content | length == 0


