download_url: https://HKXUPITD30368.hk.bocigroup.com/api/galaxy/v3/plugin/ansible/content/published/collections/artifacts/vmware-vmware-2.3.0.tar.gz
format_version: 1.0.0
name: vmware
namespace: vmware
server: https://HKXUPITD30368.hk.bocigroup.com/api/galaxy/
signatures: []
version: 2.3.0
version_url: /api/galaxy/v3/plugin/ansible/content/published/collections/index/vmware/vmware/versions/2.3.0/
